# Site settings
name: Brittany Chiang
title: Brittany Chiang | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://brittanychiang.com/
baseurl: ""
email: brittany.chiang@gmail.com
cover: https://brittanychiang.com/img/og.png
logo: https://brittanychiang.com/img/emojis/technologist.png
resume: https://brittanychiang.com/resume.pdf
social:
  - title: email
    url: mailto:koshtinikhilesh1993@gmail.com
  - title: twitter
    url: https://twitter.com/nikhilesh_kosht
  - title: instagram
    url: https://www.instagram.com/nikhilesh_koshti/
  - title: github
    url: https://github.com/koshtinikhilesh
  - title: linkedin
    url: https://www.linkedin.com/in/nikhilesh-koshti-20a8a4a3/

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
